# Generated by Django 5.1.4 on 2024-12-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='memory_percent',
        ),
        migrations.AddField(
            model_name='process',
            name='memory',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
