# Generated by Django 5.1.4 on 2024-12-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_process_memory_percent_process_memory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='memory',
            new_name='memory_percent',
        ),
    ]
