# Generated by Django 5.1.4 on 2024-12-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_memory_process_memory_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='memory_percent',
            field=models.FloatField(),
        ),
    ]
