# Generated by Django 5.1.4 on 2024-12-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_process_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
